version: 2.1
jobs:
  build:
    docker:
      - image: node
    steps:
      - run:
          command: |
            apt-get update && apt-get install git -y
      - checkout
      - run:
          command:
            npm i
      - run:
          command:
            npm i -g truffle
      - run:
          command:
            truffle compile && truffle test
